version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: class-and-object-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  web:
    image: nginx:latest
    container_name: class-and-object-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
